package org.example.problems.string.easy;

import java.util.*;
import java.util.stream.*;

/**
 * Problem: Remove Palindromic Subsequences
 * Topic: String / Two Pointers / Greedy
 * Level: Easy
 *
 * Problem Description:
 * You are given a string s consisting only of letters 'a' and 'b'. In a single step you can remove
 * one palindromic subsequence from s.
 *
 * Return the minimum number of steps to make the given string empty.
 *
 * A string is a subsequence of a given string if it is generated by deleting some characters of
 * a given string without changing its order. Note that a subsequence does not necessarily need
 * to be contiguous.
 *
 * A string is called palindrome if is one that reads the same backward as well as forward.
 *
 * Hint: Since only 'a' and 'b' are present, the answer can only be 1 (if the whole string is a palindrome) or 2 (remove all 'a's first, then all 'b's).
 *
 * Example 1:
 * Input: s = "ababa"
 * Expected Output: 1
 *
 * Example 2:
 * Input: s = "abb"
 * Expected Output: 2
 *
 * Example 3:
 * Input: s = "baabb"
 * Expected Output: 2
 *
 * Example 4:
 * Input: s = "a"
 * Expected Output: 1
 *
 * Example 5:
 * Input: s = "ab"
 * Expected Output: 2
 *
 * Constraints:
 * - 1 <= s.length() <= 10^5
 * - s[i] is either 'a' or 'b'
 *
 * Video Explanation: https://www.youtube.com/watch?v=nP7FfN0bj8c
 * LeetCode Problem Link: https://leetcode.com/problems/remove-palindromic-subsequences/
 */
public class RemovePalindromicSubsequences {

    public static void main(String[] args) {
        System.out.println("=== RemovePalindromicSubsequences ===\n");
        
        // Test case 1: Palindrome
        System.out.println("Test 1: \"ababa\"");
        System.out.println("Result: " + solution("ababa")); // 1
        System.out.println("Expected: 1\n");
        
        // Test case 2: Not palindrome
        System.out.println("Test 2: \"abb\"");
        System.out.println("Result: " + solution("abb")); // 2
        System.out.println("Expected: 2\n");
        
        // Test case 3: Complex non-palindrome
        System.out.println("Test 3: \"baabb\"");
        System.out.println("Result: " + solution("baabb")); // 2
        System.out.println("Expected: 2\n");
        
        // Test case 4: Single character
        System.out.println("Test 4: \"a\"");
        System.out.println("Result: " + solution("a")); // 1
        System.out.println("Expected: 1\n");
        
        // Test case 5: Two different characters
        System.out.println("Test 5: \"ab\"");
        System.out.println("Result: " + solution("ab")); // 2
        System.out.println("Expected: 2\n");
        
        // Test case 6: All same character
        System.out.println("Test 6: \"aaaa\"");
        System.out.println("Result: " + solution("aaaa")); // 1
        System.out.println("Expected: 1\n");
        
        System.out.println("=== Alternative Solution (Stream API) ===\n");
        
        // Alternative solution tests
        System.out.println("Alt Test 1: \"ababa\"");
        System.out.println("Result: " + alternativeSolution("ababa")); // 1
        System.out.println("Expected: 1\n");
        
        System.out.println("Alt Test 2: \"abb\"");
        System.out.println("Result: " + alternativeSolution("abb")); // 2
        System.out.println("Expected: 2\n");
    }

    /**
     * Solution 1: Two-Pointer Palindrome Check
     * 
     * Time Complexity: O(n) where n is the length of the string
     * Space Complexity: O(1) no extra space needed
     * 
     * Algorithm:
     * - Check if the string is a palindrome using two pointers
     * - Left pointer starts at 0, right pointer starts at length-1
     * - Compare characters moving inward
     * - If entire string is palindrome: return 1
     * - Otherwise: return 2 (we can always remove all 'a's or all 'b's as palindromes)
     * 
     * Key Insight:
     * Since we only have 'a' and 'b':
     * - Any string of all 'a's is a palindrome
     * - Any string of all 'b's is a palindrome
     * - So we can ALWAYS remove the string in at most 2 steps:
     *   Step 1: Remove all 'a's as a subsequence (which is a palindrome)
     *   Step 2: Remove all 'b's as a subsequence (which is a palindrome)
     * - If the entire string is already a palindrome, we can do it in 1 step
     * 
     * Example: "abb"
     * - Not a palindrome (first 'a', last 'b')
     * - Return 2
     * - Why? We can remove "a" (palindrome) and then "bb" (palindrome)
     */
    public static int solution(String s) {
        // Check if string is a palindrome
        if (isPalindrome(s)) {
            return 1;  // Entire string can be removed in one step
        } else {
            return 2;  // Can always remove in 2 steps (all 'a's then all 'b's)
        }
    }

    /**
     * Solution 2: Stream API Palindrome Check
     * 
     * Time Complexity: O(n) where n is the length of the string
     * Space Complexity: O(n) for the streams
     * 
     * Algorithm:
     * - Use Stream API to:
     *   1. Convert string to character stream
     *   2. Collect to list
     *   3. Compare with reversed list using streams
     * - If they match (palindrome): return 1
     * - Otherwise: return 2
     * 
     * Advantages:
     * - Functional programming style
     * - More expressive and declarative
     * - Easier to chain operations
     * 
     * Trade-offs:
     * - More overhead due to stream operations
     * - Uses more memory for intermediate collections
     * - Less efficient than two-pointer approach for large strings
     * 
     * Example: "ababa"
     * - Convert to chars: [a, b, a, b, a]
     * - Reverse: [a, b, a, b, a]
     * - Match: Yes → return 1
     */
    public static int alternativeSolution(String s) {
        // A simpler stream-based palindrome check using the helper method
        boolean isPalindrome = isPalindromeWithStream(s);

        if (isPalindrome) {
            return 1;
        } else {
            return 2;
        }
    }

    /**
     * Helper Method 1: Two-Pointer Palindrome Check
     * 
     * @param s the string to check
     * @return true if s is a palindrome, false otherwise
     */
    private static boolean isPalindrome(String s) {
        int left = 0, right = s.length() - 1;
        
        while (left < right) {
            if (s.charAt(left) != s.charAt(right)) {
                return false;
            }
            left++;
            right--;
        }
        
        return true;
    }

    /**
     * Helper Method 2: Stream-Based Palindrome Check
     * 
     * Algorithm:
     * - Convert string to character array
     * - Use IntStream to iterate through first half
     * - Compare each character with its mirror from the end
     * - If any mismatch found, return false
     * - Otherwise return true
     * 
     * Time: O(n/2) = O(n)
     * Space: O(n) for character array
     * 
     * @param s the string to check
     * @return true if s is a palindrome, false otherwise
     */
    private static boolean isPalindromeWithStream(String s) {
        char[] chars = s.toCharArray();
        
        return IntStream.range(0, chars.length / 2)
                .allMatch(i -> chars[i] == chars[chars.length - 1 - i]);
    }
}
